# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

os: linux
dist: xenial

before_install:
 - openssl aes-256-cbc -K $encrypted_69026ffcf008_key -iv $encrypted_69026ffcf008_iv
   -in aula-devops-cloud-0dc060e083a0.json.enc -out ../aula-devops-cloud-0dc060e083a0.json
   -d

jobs:
  include:
   - stage: Build

     name: "Testes unitarios"
     # Instalação de Módulos que são necessários para a Aplicação.
     install:
      - pip install flask flask-wtf coverage
      # Defini o script de Teste que deve rodar toda vez que o código for alterado.
      script:
       - coverage run test.py || travis_terminate 1;
       - coverage report app.py || travis_terminate 1;
       - coverage xml app.py || travis_terminate 1;

   - stage: STG Deploy
     script: skip
     # Definir o Deploy no Heroku
     deploy:
      provider: heroku
      api_key: $HEROKU_API_KEY
      edge: true 
      app: deveopslab
      on:
       branch: main

   - stage: STG TEST
     script:
      - curl https://deveopslab.herokuapp.com/ | grep Hello || travis_terminate 1;

   - stage: PROD Deploy
     script: skip
     #Definir o deploy no google appEngine
     deploy:
      provider: gae
      keyfile: ../aula-devops-cloud-0dc060e083a0.json
      project: aula-devops-cloud
      on:
       branch: main

   - stage: PROD TEST
     script:
      - curl https://aula-devops-cloud.uc.r.appspot.com/
